-- SUPORTE
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_joao_bosco','$2a$12$wYbVwSLX4c0Tof36W3qDweWY5qdD0L.UezY7hMqZHnEL33lTwd9YC', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_joao_bosco');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_joao_bosco'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_joao_bosco'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_roberta_castro','$2a$12$D5PNfg1FRas0vvobBo3JAOaYfNJ4Nt8X.ija4p8sC0fh0A0/HLBZK', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_roberta_castro');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_roberta_castro'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_roberta_castro'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_natan_oliveira','$2a$12$ZaklzcB2ogcN0HNyvdFELesYODoL5JvqWd.04DAxV33kNsWdncOem', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_natan_oliveira');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_natan_oliveira'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_natan_oliveira'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_gabriel_lopes','$2a$12$V.e13yBrYtZu.L9NnywSSOVVbkBcHmtdF352tNHS6BaUq4Bx3n8hy', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_gabriel_lopes');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_gabriel_lopes'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_gabriel_lopes'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_ervansuer_igor','$2a$12$YU1JEzzwuAKZjN8tXWrsJuF69gF3e2hTgW0bhAt4oPoRTmIFxiyz.', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_ervansuer_igor');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_ervansuer_igor'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_ervansuer_igor'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_maria_thaynnara','$2a$12$xYNrvyVBLT85pNLsalZOQ.rhFN713WjjkueArJkWnbhkdJWkNCa6m', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_maria_thaynnara');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_maria_thaynnara'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_maria_thaynnara'));
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_samile_ingrid','$2a$12$OXpVqpLrLeyttfK5QraenekPMjCQiw3Wrcxjb2otIfuARECWfyupW', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_samile_ingrid');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_samile_ingrid'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_samile_ingrid'));

-- IMP
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_imp','$2a$12$9Y5EpdNnHg76FGrIBjEwXulbfiUTrCbmemujhXRK0gx7i3hGT3Hmy', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_imp');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_imp'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_imp'));

-- INF
INSERT INTO usuario (login, senha, status, id_centrodistribuicao, id_empresa)SELECT 'ptf_infra','$2a$12$h6XVj1auhdhFQwpV3o3X5.J8aTu1m3cPHFH2EItXBliyApGyNekvu', 'ATIVO', 1, (SELECT min(id) FROM empresa) WHERE NOT EXISTS (SELECT 1 FROM usuario WHERE login = 'ptf_infra');	INSERT INTO public.usuario_papeis (usuario, papel) SELECT (SELECT id FROM usuario WHERE login ='ptf_infra'),'ROLE_ADMINISTRADOR' WHERE NOT EXISTS (SELECT 1 FROM usuario_papeis WHERE usuario = (SELECT id FROM usuario WHERE login = 'ptf_infra'));