ALTER TABLE empresa ADD COLUMN IF NOT EXISTS soap_simulacao_config CHARACTER VARYING(40) NOT NULL DEFAULT 'PADARO_WINTHOR';
			
INSERT INTO versaoBanco(versao)
VALUES ('9.0.0.2-21')
ON CONFLICT (versao)
DO NOTHING;